# Generated by Django 6.1.1 on 2026-09-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('file', models.FileField(upload_to='audio/', verbose_name='файл')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='длительность, с')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='язык')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='загружен')),
            ],
            options={
                'verbose_name': 'аудиофайл',
                'verbose_name_plural': 'аудиофайлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('start', models.FloatField(verbose_name='начало, с')),
                ('end', models.FloatField(verbose_name='конец, с')),
                ('text', models.TextField(verbose_name='текст')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='player.audiofile')),
            ],
            options={
                'ordering': ['audio', 'index'],
                'constraints': [models.UniqueConstraint(fields=('audio', 'index'), name='unique_segment_index')],
            },
        ),
    ]
