# Generated by Django 6.1.1 on 2026-09-30 05:10

from django.db import migrations, models

from player.models import parse_call_name


def fill_call_details(apps, schema_editor):
    AudioFile = apps.get_model('player', 'AudioFile')
    for audio in AudioFile.objects.filter(call_id=''):
        if info := parse_call_name(audio.file.name):
            AudioFile.objects.filter(pk=audio.pk).update(**info)


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-call_started_at', '-created_at'], 'verbose_name': 'аудиофайл', 'verbose_name_plural': 'аудиофайлы'},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='call_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID звонка'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='call_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время звонка'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='operator',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='номер оператора'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='номер телефона'),
        ),
        migrations.RunPython(fill_call_details, migrations.RunPython.noop),
    ]
