# Generated by Django 6.1.1 on 2026-09-30 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_call_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbx_url', models.URLField(blank=True, help_text='Например, https://192.168.1.10', verbose_name='адрес АТС')),
                ('pbx_username', models.CharField(blank=True, max_length=150, verbose_name='логин АТС')),
                ('pbx_verify_ssl', models.BooleanField(default=False, help_text='У АТС в локальной сети обычно самоподписанный сертификат — тогда выключено.', verbose_name='проверять SSL-сертификат АТС')),
                ('controller', models.CharField(blank=True, help_text='Например, ИБ', max_length=16, verbose_name='инициалы контролёра')),
                ('min_duration', models.PositiveIntegerField(default=30, help_text='Более короткие звонки (недозвоны, сбросы) не скачиваются.', verbose_name='мин. длительность звонка, с')),
                ('worker_seen_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='PbxSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='день звонков')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Скачивается'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('found', models.PositiveIntegerField(default=0, verbose_name='найдено')),
                ('downloaded', models.PositiveIntegerField(default=0, verbose_name='скачано')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='уже были')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
            ],
            options={
                'verbose_name': 'загрузка из АТС',
                'verbose_name_plural': 'загрузки из АТС',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата контроля')),
                ('interviewer', models.CharField(blank=True, max_length=120, verbose_name='интервьюер')),
                ('respondent_id', models.CharField(blank=True, max_length=64, verbose_name='ID респондента')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город проживания')),
                ('listen_city', models.CharField(blank=True, max_length=100, verbose_name='город слушания')),
                ('stations', models.CharField(blank=True, max_length=255, verbose_name='радиостанции / не слушал')),
                ('has_errors', models.BooleanField(default=False, verbose_name='ошибки')),
                ('error_comment', models.TextField(blank=True, verbose_name='комментарий к ошибкам')),
                ('result', models.CharField(blank=True, choices=[('ок', 'ок'), ('ошибка', 'ошибка'), ('брак', 'брак')], max_length=16, verbose_name='результат')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('fixed', models.CharField(blank=True, max_length=100, verbose_name='исправлено')),
                ('controller', models.CharField(blank=True, max_length=16, verbose_name='контроль')),
                ('completed', models.BooleanField(default=False, verbose_name='проверено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='player.audiofile')),
            ],
            options={
                'verbose_name': 'контроль звонка',
                'verbose_name_plural': 'контроль звонков',
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_index=True, max_length=16, verbose_name='внутр. номер')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'интервьюер',
                'verbose_name_plural': 'интервьюеры',
                'ordering': ['extension', 'name'],
                'constraints': [models.UniqueConstraint(fields=('extension', 'name'), name='unique_interviewer')],
            },
        ),
        migrations.AddField(
            model_name='audiofile',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_files', to='player.pbxsync', verbose_name='загрузка из АТС'),
        ),
        migrations.AddConstraint(
            model_name='audiofile',
            constraint=models.UniqueConstraint(condition=models.Q(('call_id', ''), _negated=True), fields=('call_id',), name='unique_call_id'),
        ),
    ]
