# Generated by Django 6.1.1 on 2026-09-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_qa_review_and_pbx_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='stations',
            field=models.TextField(blank=True, default='Авторадио\nДельта\nДушевное\nНовое\nРадио Витебск\nРадио Могилев\nРадиус\nРокс\nРусское\nЮмор\nЮнистар', help_text='По одной на строку, в том написании, как в отчёте. ИИ сверяет с этим списком искажённые распознаванием названия.', verbose_name='радиостанции'),
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город проживания')),
                ('listen_city', models.CharField(blank=True, max_length=100, verbose_name='город слушания')),
                ('stations', models.CharField(blank=True, max_length=255, verbose_name='радиостанции / не слушал')),
                ('notes', models.TextField(blank=True, verbose_name='пояснение')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='модель')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='токенов на входе')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='токенов на выходе')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='player.audiofile')),
            ],
            options={
                'verbose_name': 'анализ ИИ',
                'verbose_name_plural': 'анализ ИИ',
            },
        ),
    ]
