# Generated by Django 6.1.1 on 2026-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_call_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('report_name', models.CharField(blank=True, help_text='Как писать в колонку «Радиостанции» отчёта. Пусто — как название.', max_length=120, verbose_name='в отчёте')),
                ('aliases', models.TextField(blank=True, help_text='Через запятую: английское, прежнее, как говорят респонденты.', verbose_name='другие названия')),
                ('frequencies', models.JSONField(blank=True, default=dict, verbose_name='частоты')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('active', models.BooleanField(default=True, verbose_name='использовать')),
            ],
            options={
                'verbose_name': 'радиостанция',
                'verbose_name_plural': 'радиостанции',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='stations',
        ),
    ]
