# Generated by Django 6.1.1 on 2026-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_radio_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiostation',
            name='aliases',
            field=models.TextField(blank=True, help_text='Через «;»: английское, прежнее, как говорят респонденты.', verbose_name='другие названия'),
        ),
    ]
