# Generated by Django 6.1.1 on 2026-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_radio_station_alias_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='max_duration',
            field=models.PositiveIntegerField(default=900, help_text='Длиннее не скачиваются. 0 — без ограничения.', verbose_name='макс. длительность звонка, с'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='min_duration',
            field=models.PositiveIntegerField(default=80, help_text='Короче не скачиваются (недозвоны, сбросы). Как «Длительность: между» в «Отчётах CDR».', verbose_name='мин. длительность звонка, с'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='pbx_url',
            field=models.URLField(blank=True, help_text='Например, http://192.168.3.80', verbose_name='адрес АТС'),
        ),
    ]
