# Generated by Django 6.1.1 on 2026-10-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_pbx_duration_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbxsync',
            name='failed',
            field=models.PositiveIntegerField(default=0, verbose_name='не скачано'),
        ),
    ]
