# Generated by Django 6.1.1 on 2026-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_pbx_sync_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='survey_url',
            field=models.CharField(blank=True, help_text='Адрес страницы CRM с ответами респондента. Подстановки: {phone} — 375291234567, {phone_local} — 291234567, {date} — 2026-09-29, {date_ru} — 29.09.2026, {time} — 14:01, {operator} — 301, {call_id}. Пусто — панели анкеты нет.', max_length=500, verbose_name='ссылка на анкету оператора'),
        ),
    ]
