# Generated by Django 6.1.1 on 2026-10-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_survey_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='crm_url',
            field=models.URLField(blank=True, help_text='CRM с анкетами операторов, например http://192.168.12.230. SyncVoice сам находит анкету звонка.', verbose_name='адрес CRM'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='crm_username',
            field=models.CharField(blank=True, help_text='Отдельная учётная запись для SyncVoice. Через SyncVoice анкеты только просматриваются.', max_length=150, verbose_name='логин CRM (email)'),
        ),
    ]
