# Generated by Django 6.1.1 on 2026-10-01 18:08

from django.conf import settings
from django.db import migrations, models

import player.audio_paths


def move_into_day_folders(apps, schema_editor):
    AudioFile = apps.get_model('player', 'AudioFile')
    player.audio_paths.relocate(AudioFile, settings.MEDIA_ROOT)


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_crm_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(max_length=255, upload_to=player.audio_paths.audio_upload_to, verbose_name='файл'),
        ),
        # media/audio/<file> -> media/audio/<year>/<month>/<day>/<file>, by call date.
        migrations.RunPython(move_into_day_folders, migrations.RunPython.noop),
    ]
