# Generated by Django 6.1.1 on 2026-10-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_audio_day_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='статус')),
                ('survey_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='анкета CRM')),
                ('discrepancies', models.JSONField(blank=True, default=list, verbose_name='расхождения')),
                ('summary', models.TextField(blank=True, verbose_name='итог')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='модель')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='токенов на входе')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='токенов на выходе')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='player.audiofile')),
            ],
            options={
                'verbose_name': 'сверка с анкетой',
                'verbose_name_plural': 'сверки с анкетой',
            },
        ),
    ]
