# Generated by Django 6.1.1 on 2026-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_call_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ai_compare_model',
            field=models.CharField(blank=True, help_text='Сверке нужно больше рассуждений — можно взять модель сильнее, например gemini-3.8-flash. Пусто — та же, что для подсказок.', max_length=64, verbose_name='модель для сверки анкеты'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Например, gemini-3.1-flash-lite. Пусто — из файла .env (GEMINI_MODEL).', max_length=64, verbose_name='модель для подсказок полей'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_rules_analysis',
            field=models.TextField(blank=True, help_text='Своими словами, по одному правилу на строку. Добавляются к встроенному промпту и важнее его общих правил.', verbose_name='дополнительные правила для подсказок полей'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_rules_compare',
            field=models.TextField(blank=True, help_text='Например: «Ответ "где-то половина" — граница, оператор должен уточнить». Добавляются к встроенному промпту и важнее его общих правил.', verbose_name='дополнительные правила для сверки анкеты'),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Первые знаки хэша промпта, с которым сделан ответ.', max_length=16, verbose_name='версия промпта'),
        ),
        migrations.AddField(
            model_name='callcomparison',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='Первые знаки хэша промпта, с которым сделан ответ.', max_length=16, verbose_name='версия промпта'),
        ),
    ]
