# Generated by Django 6.1.1 on 2026-10-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_ai_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64, unique=True, verbose_name='модель')),
                ('exhausted_until', models.DateTimeField(verbose_name='лимит исчерпан до')),
            ],
            options={
                'verbose_name': 'дневной лимит Gemini',
                'verbose_name_plural': 'дневные лимиты Gemini',
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ai_fallback_models',
            field=models.CharField(blank=True, help_text='Через запятую, по порядку, например: gemini-3.5-flash-lite, gemini-2.5-flash-lite. Когда у модели кончается дневной лимит бесплатного тарифа, SyncVoice переходит на следующую до сброса лимита (полночь по Калифорнии — 10–11 утра по Минску).', max_length=300, verbose_name='запасные модели'),
        ),
    ]
