# Generated by Django 6.1.1 on 2026-10-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_gemini_fallback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='ai_compare_model',
            field=models.CharField(blank=True, help_text='Сверке нужно больше рассуждений — можно взять модель сильнее, например gemini-3.8-flash. Пусто — из файла .env (GEMINI_COMPARE_MODEL), а если и там пусто — та же, что для подсказок.', max_length=64, verbose_name='модель для сверки анкеты'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Например, gemini-3.1-flash-lite. Пусто — из файла .env (GEMINI_MODEL), а если и там пусто — gemini-3.1-flash-lite.', max_length=64, verbose_name='модель для подсказок полей'),
        ),
    ]
