# Generated by Django 6.1.1 on 2026-10-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_model_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcomparison',
            name='respondent_name',
            field=models.CharField(blank=True, help_text='Из анкеты CRM — для списка звонков. В Gemini не отправляется.', max_length=100, verbose_name='имя респондента'),
        ),
    ]
