# Generated by Django 6.1.1 on 2026-10-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_respondent_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['audio', 'index'], 'verbose_name': 'строка субтитров', 'verbose_name_plural': 'субтитры'},
        ),
        migrations.AlterField(
            model_name='segment',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='player.audiofile', verbose_name='звонок'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='index',
            field=models.PositiveIntegerField(verbose_name='№'),
        ),
    ]
