# Generated by Django 6.1.1 on 2026-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_segment_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiPace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64, unique=True, verbose_name='модель')),
                ('next_slot_at', models.DateTimeField(verbose_name='следующий запрос не раньше')),
            ],
            options={
                'verbose_name': 'темп запросов Gemini',
                'verbose_name_plural': 'темп запросов Gemini',
            },
        ),
    ]
