"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import shutil
import sys
from pathlib import Path

import certifi
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets and per-machine options (API keys, proxy) live in BASE_DIR/.env,
# which is git-ignored; see .env.example. Real environment variables win.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6u1=u9u=imn!lqtb_dk%ak_36*5c1t8(ewp-#=!2_i-!by^zc&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# The app runs locally on the user's machine (waitress binds to 127.0.0.1).
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Keep the link to the CRM survey window we open, so «Окно рядом» is reused
# (Django's default 'same-origin' cuts it and every call opens a new window).
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'player',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # The worker thread, web requests and manage.py commands (separate processes) write
        # concurrently. WAL lets readers and the writer work at once; IMMEDIATE transactions
        # wait for the write lock (timeout, seconds) instead of failing with «database is locked».
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
            'init_command': 'PRAGMA journal_mode=WAL;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

# Call times in recording file names are local (Minsk) time.
TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Served by WhiteNoise straight from the apps' static/ dirs (no collectstatic),
# so it works under waitress as well as runserver.
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Uploaded audio files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
# A day of calls (~130 WAV files) can be uploaded at once; Django's default is 100.
DATA_UPLOAD_MAX_NUMBER_FILES = 1000


# Whisper
# Model: tiny, base, small, medium, large. Bigger is more accurate but slower.
# Language: 'ru' by default (calls are in Russian); set WHISPER_LANGUAGE=auto to detect.

WHISPER_MODEL = os.environ.get('WHISPER_MODEL', 'small')
# faster-whisper or openai-whisper; see player/transcription.py. On macOS
# (Intel) openai-whisper is much faster, elsewhere faster-whisper is expected
# to be — check with `manage.py asr_benchmark`.
WHISPER_ENGINE = os.environ.get(
    'WHISPER_ENGINE', 'openai-whisper' if sys.platform == 'darwin' else 'faster-whisper',
)
WHISPER_LANGUAGE = os.environ.get('WHISPER_LANGUAGE', 'ru')
if WHISPER_LANGUAGE == 'auto':
    WHISPER_LANGUAGE = None

# python.org builds of Python ship without root certificates, so downloading
# Whisper models fails with CERTIFICATE_VERIFY_FAILED. Use certifi's bundle.
os.environ.setdefault('SSL_CERT_FILE', certifi.where())


# Gemini — suggests «Город проживания», «Город слушания», «Радиостанции»
# from the transcript (player/analysis.py). Off while GEMINI_API_KEY is empty.
# The proxy applies to Gemini requests only (not to the PBX or model downloads).

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-3.8-flash')
# Survey check against the CRM (harder reasoning); empty — the same as GEMINI_MODEL.
GEMINI_COMPARE_MODEL = os.environ.get('GEMINI_COMPARE_MODEL', '')
GEMINI_PROXY_URL = os.environ.get('GEMINI_PROXY_URL', '')  # e.g. http://1.2.3.4:3128
GEMINI_PROXY_USERNAME = os.environ.get('GEMINI_PROXY_USERNAME', '')
GEMINI_PROXY_PASSWORD = os.environ.get('GEMINI_PROXY_PASSWORD', '')


# Local read-only gateway to the operators' CRM (player/crm_proxy.py).
CRM_PROXY_PORT = int(os.environ.get('CRM_PROXY_PORT', '8766'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# FFmpeg
# Only needed by the openai-whisper fallback (faster-whisper decodes audio
# itself). Whisper calls the `ffmpeg` command by name, so put a copy of the
# imageio-ffmpeg binary named ffmpeg(.exe) into BASE_DIR/.bin and put that
# directory first on PATH. A copy, not a symlink: symlinks need admin rights
# on Windows. Override with the FFMPEG_BINARY environment variable.

try:
    import imageio_ffmpeg
except ImportError:
    imageio_ffmpeg = None

FFMPEG_BINARY = os.environ.get('FFMPEG_BINARY') or (imageio_ffmpeg and imageio_ffmpeg.get_ffmpeg_exe())

if FFMPEG_BINARY:
    _ffmpeg_dir = BASE_DIR / '.bin'
    _ffmpeg_copy = _ffmpeg_dir / ('ffmpeg.exe' if os.name == 'nt' else 'ffmpeg')
    _source = Path(FFMPEG_BINARY)
    if not _ffmpeg_copy.exists() or _ffmpeg_copy.stat().st_size != _source.stat().st_size:
        _ffmpeg_dir.mkdir(exist_ok=True)
        _ffmpeg_copy.unlink(missing_ok=True)  # also removes an old symlink
        shutil.copy2(_source, _ffmpeg_copy)
    os.environ['PATH'] = f"{_ffmpeg_dir}{os.pathsep}{os.environ.get('PATH', '')}"
