"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import certifi
import imageio_ffmpeg

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6u1=u9u=imn!lqtb_dk%ak_36*5c1t8(ewp-#=!2_i-!by^zc&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'player',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

# Call times in recording file names are local (Minsk) time.
TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Uploaded audio files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Whisper
# Model: tiny, base, small, medium, large. Bigger is more accurate but slower.
# Language: e.g. 'ru', or None to auto-detect.

WHISPER_MODEL = os.environ.get('WHISPER_MODEL', 'small')
WHISPER_LANGUAGE = os.environ.get('WHISPER_LANGUAGE') or None

# python.org builds of Python ship without root certificates, so downloading
# Whisper models fails with CERTIFICATE_VERIFY_FAILED. Use certifi's bundle.
os.environ.setdefault('SSL_CERT_FILE', certifi.where())


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# FFmpeg
# Whisper calls the `ffmpeg` command by name, so expose the binary under that
# name in BASE_DIR/.bin and put that directory first on PATH.
# Override with the FFMPEG_BINARY environment variable.

FFMPEG_BINARY = os.environ.get('FFMPEG_BINARY') or imageio_ffmpeg.get_ffmpeg_exe()

_ffmpeg_dir = BASE_DIR / '.bin'
_ffmpeg_link = _ffmpeg_dir / 'ffmpeg'
if not _ffmpeg_link.exists() or _ffmpeg_link.resolve() != Path(FFMPEG_BINARY).resolve():
    _ffmpeg_dir.mkdir(exist_ok=True)
    _ffmpeg_link.unlink(missing_ok=True)
    _ffmpeg_link.symlink_to(FFMPEG_BINARY)
os.environ['PATH'] = f"{_ffmpeg_dir}{os.pathsep}{os.environ.get('PATH', '')}"
